# Generated by Django 3.1.7 on 2021-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20210401_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='snippet',
            field=models.CharField(default='Descripción del evento', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Descripción de la publicación', max_length=255),
        ),
    ]
