# Generated by Django 3.1.7 on 2021-04-08 03:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_blogtransversalpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtransversalpost',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('awdawd', 'awdawd'), ('Hola categoria 1', 'Hola categoria 1'), ('Categoria 2', 'Categoria 2')], max_length=35),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('awdawd', 'awdawd'), ('Hola categoria 1', 'Hola categoria 1'), ('Categoria 2', 'Categoria 2')], max_length=35),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('awdawd', 'awdawd'), ('Hola categoria 1', 'Hola categoria 1'), ('Categoria 2', 'Categoria 2')], max_length=35),
        ),
    ]
