# Generated by Django 3.1.7 on 2021-04-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_auto_20210401_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(max_length=255),
        ),
    ]
