# Generated by Django 3.1.7 on 2021-04-09 17:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.AlterField(
            model_name='blogtransversalpost',
            name='author',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diego', 'Arana Ballesteros')], max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diego', 'Arana Ballesteros')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diego', 'Arana Ballesteros')], max_length=5),
        ),
        migrations.DeleteModel(
            name='DatosDuros',
        ),
    ]
