# Generated by Django 3.1.7 on 2021-04-09 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0009_auto_20210409_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtransversalpost',
            name='author',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diego Arana Ballesteros', 'Diego Arana Ballesteros'), ('Diego Arana Ballesteros2', 'Diego Arana Ballesteros2')], max_length=48),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diego Arana Ballesteros', 'Diego Arana Ballesteros'), ('Diego Arana Ballesteros2', 'Diego Arana Ballesteros2')], max_length=48),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diego Arana Ballesteros', 'Diego Arana Ballesteros'), ('Diego Arana Ballesteros2', 'Diego Arana Ballesteros2')], max_length=48),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
