# Generated by Django 3.1.7 on 2021-04-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_auto_20210401_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='micrositios',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
