# Generated by Django 3.1.7 on 2021-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Biografía'),
        ),
    ]
