# Generated by Django 3.1.7 on 2021-04-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0014_auto_20210412_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='fileDownload',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
