# Generated by Django 3.1.7 on 2021-04-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_lectura_filedownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtransversalpost',
            name='optional_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='optional_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='optional_author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
